version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wasim
      - POSTGRES_PASSWORD=wasim2263
      - POSTGRES_DB=django_app_docker

  celery:
    build: .
    command: celery worker --app=django_docker --loglevel=info -Q default,priority_high
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data:
