version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wasim
      - POSTGRES_PASSWORD=wasim2263
      - POSTGRES_DB=django_app_docker

  celery:
    build: .
    command: celery worker --app=django_docker --loglevel=info --concurrency=10 -Q default,priority_high
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  celery_single:
    build: .
    command: celery worker --app=django_docker --loglevel=info --concurrency=1 -Q single_queue
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  celery_beat:
    build: .
    command: celery -A django_docker beat -l info  --pidfile=
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  redis:
    image: redis:6-alpine
  dashboard:
    build: .
    command: flower -A django_docker --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery
      - celery_single
      - celery_beat

volumes:
  postgres_data:
